services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginx-proxy-manager'
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
      - ${MANAGER_PORT}:81
    volumes:
      - ./nginx-data:/data
      - ./nginx-letsencrypt:/etc/letsencrypt
      - ./nginx-snippets:/snippets:ro
    environment:
      TZ: ${TZ}